In [27]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)

In [28]:
dataDir = '../data/all/'

# application data

In [29]:
application_train = pd.read_csv( dataDir + 'application_train.csv' )

In [30]:
application_train.head(5)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
# look at ddata types of each colum
print application_train.dtypes

SK_ID_CURR                        int64
TARGET                            int64
NAME_CONTRACT_TYPE               object
CODE_GENDER                      object
FLAG_OWN_CAR                     object
FLAG_OWN_REALTY                  object
CNT_CHILDREN                      int64
AMT_INCOME_TOTAL                float64
AMT_CREDIT                      float64
AMT_ANNUITY                     float64
AMT_GOODS_PRICE                 float64
NAME_TYPE_SUITE                  object
NAME_INCOME_TYPE                 object
NAME_EDUCATION_TYPE              object
NAME_FAMILY_STATUS               object
NAME_HOUSING_TYPE                object
REGION_POPULATION_RELATIVE      float64
DAYS_BIRTH                        int64
DAYS_EMPLOYED                     int64
DAYS_REGISTRATION               float64
DAYS_ID_PUBLISH                   int64
OWN_CAR_AGE                     float64
FLAG_MOBIL                        int64
FLAG_EMP_PHONE                    int64
FLAG_WORK_PHONE                   int64
FLAG_CONT_MOBILE                  int64
FLAG_PHONE                        int64
FLAG_EMAIL                        int64
OCCUPATION_TYPE                  object
CNT_FAM_MEMBERS                 float64
REGION_RATING_CLIENT              int64
REGION_RATING_CLIENT_W_CITY       int64
WEEKDAY_APPR_PROCESS_START       object
HOUR_APPR_PROCESS_START           int64
REG_REGION_NOT_LIVE_REGION        int64
REG_REGION_NOT_WORK_REGION        int64
LIVE_REGION_NOT_WORK_REGION       int64
REG_CITY_NOT_LIVE_CITY            int64
REG_CITY_NOT_WORK_CITY            int64
LIVE_CITY_NOT_WORK_CITY           int64
ORGANIZATION_TYPE                object
EXT_SOURCE_1                    float64
EXT_SOURCE_2                    float64
EXT_SOURCE_3                    float64
APARTMENTS_AVG                  float64
BASEMENTAREA_AVG                float64
YEARS_BEGINEXPLUATATION_AVG     float64
YEARS_BUILD_AVG                 float64
COMMONAREA_AVG                  float64
ELEVATORS_AVG                   float64
ENTRANCES_AVG                   float64
FLOORSMAX_AVG                   float64
FLOORSMIN_AVG                   float64
LANDAREA_AVG                    float64
LIVINGAPARTMENTS_AVG            float64
LIVINGAREA_AVG                  float64
NONLIVINGAPARTMENTS_AVG         float64
NONLIVINGAREA_AVG               float64
APARTMENTS_MODE                 float64
BASEMENTAREA_MODE               float64
YEARS_BEGINEXPLUATATION_MODE    float64
YEARS_BUILD_MODE                float64
COMMONAREA_MODE                 float64
ELEVATORS_MODE                  float64
ENTRANCES_MODE                  float64
FLOORSMAX_MODE                  float64
FLOORSMIN_MODE                  float64
LANDAREA_MODE                   float64
LIVINGAPARTMENTS_MODE           float64
LIVINGAREA_MODE                 float64
NONLIVINGAPARTMENTS_MODE        float64
NONLIVINGAREA_MODE              float64
APARTMENTS_MEDI                 float64
BASEMENTAREA_MEDI               float64
YEARS_BEGINEXPLUATATION_MEDI    float64
YEARS_BUILD_MEDI                float64
COMMONAREA_MEDI                 float64
ELEVATORS_MEDI                  float64
ENTRANCES_MEDI                  float64
FLOORSMAX_MEDI                  float64
FLOORSMIN_MEDI                  float64
LANDAREA_MEDI                   float64
LIVINGAPARTMENTS_MEDI           float64
LIVINGAREA_MEDI                 float64
NONLIVINGAPARTMENTS_MEDI        float64
NONLIVINGAREA_MEDI              float64
FONDKAPREMONT_MODE               object
HOUSETYPE_MODE                   object
TOTALAREA_MODE                  float64
WALLSMATERIAL_MODE               object
EMERGENCYSTATE_MODE              object
OBS_30_CNT_SOCIAL_CIRCLE        float64
DEF_30_CNT_SOCIAL_CIRCLE        float64
OBS_60_CNT_SOCIAL_CIRCLE        float64
DEF_60_CNT_SOCIAL_CIRCLE        float64
DAYS_LAST_PHONE_CHANGE          float64
FLAG_DOCUMENT_2                   int64
FLAG_DOCUMENT_3                   int64
FLAG_DOCUMENT_4                   int64
FLAG_DOCUMENT_5                   int64
FLAG_DOCUMENT_6                   int64
FLAG_DOCUMENT_7                   int64
FLAG_DOCUMENT_8                   int64
FLAG_DOCUMENT_9                   int64
FLAG_DOCUMENT_10                  int64
FLAG_DOCUMENT_11                  int64
FLAG_DOCUMENT_12                  int64
FLAG_DOCUMENT_13                  int64
FLAG_DOCUMENT_14                  int64
FLAG_DOCUMENT_15                  int64
FLAG_DOCUMENT_16                  int64
FLAG_DOCUMENT_17                  int64
FLAG_DOCUMENT_18                  int64
FLAG_DOCUMENT_19                  int64
FLAG_DOCUMENT_20                  int64
FLAG_DOCUMENT_21                  int64
AMT_REQ_CREDIT_BUREAU_HOUR      float64
AMT_REQ_CREDIT_BUREAU_DAY       float64
AMT_REQ_CREDIT_BUREAU_WEEK      float64
AMT_REQ_CREDIT_BUREAU_MON       float64
AMT_REQ_CREDIT_BUREAU_QRT       float64
AMT_REQ_CREDIT_BUREAU_YEAR      float64
dtype: object

In [32]:
#list( application_train.columns )
y = application_train['TARGET']
X = application_train.drop('TARGET', axis = 1)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.1, random_state=42 )

In [33]:
# one hot encoding for categorical variables
one_hot_encoded_X_train = pd.get_dummies(X_train)
one_hot_encoded_X_test = pd.get_dummies(X_test)
encoded_X_train, encoded_X_test = one_hot_encoded_X_train.align(one_hot_encoded_X_test,
                                                                    join='left', 
                                                                    axis=1)

In [34]:
# check the columns after one hot encoding
print encoded_X_train.columns

Index([u'SK_ID_CURR', u'CNT_CHILDREN', u'AMT_INCOME_TOTAL', u'AMT_CREDIT',
       u'AMT_ANNUITY', u'AMT_GOODS_PRICE', u'REGION_POPULATION_RELATIVE',
       u'DAYS_BIRTH', u'DAYS_EMPLOYED', u'DAYS_REGISTRATION',
       ...
       u'HOUSETYPE_MODE_terraced house', u'WALLSMATERIAL_MODE_Block',
       u'WALLSMATERIAL_MODE_Mixed', u'WALLSMATERIAL_MODE_Monolithic',
       u'WALLSMATERIAL_MODE_Others', u'WALLSMATERIAL_MODE_Panel',
       u'WALLSMATERIAL_MODE_Stone, brick', u'WALLSMATERIAL_MODE_Wooden',
       u'EMERGENCYSTATE_MODE_No', u'EMERGENCYSTATE_MODE_Yes'],
      dtype='object', length=245)

In [35]:
print X_train.shape
print encoded_X_train.shape

(276759, 121)
(276759, 245)

In [ ]:
# handle missiong values
columns = X_train.columns
missing_val_count_by_column = (X_train.isnull().sum())
print missing_val_count_by_column / float(X_train.shape[0])
# check if there is any missing y
print y_train.isnull().sum(), y_test.isnull().sum()

SK_ID_CURR                      0.000000
NAME_CONTRACT_TYPE              0.000000
CODE_GENDER                     0.000000
FLAG_OWN_CAR                    0.000000
FLAG_OWN_REALTY                 0.000000
CNT_CHILDREN                    0.000000
AMT_INCOME_TOTAL                0.000000
AMT_CREDIT                      0.000000
AMT_ANNUITY                     0.000036
AMT_GOODS_PRICE                 0.000896
NAME_TYPE_SUITE                 0.004220
NAME_INCOME_TYPE                0.000000
NAME_EDUCATION_TYPE             0.000000
NAME_FAMILY_STATUS              0.000000
NAME_HOUSING_TYPE               0.000000
REGION_POPULATION_RELATIVE      0.000000
DAYS_BIRTH                      0.000000
DAYS_EMPLOYED                   0.000000
DAYS_REGISTRATION               0.000000
DAYS_ID_PUBLISH                 0.000000
OWN_CAR_AGE                     0.659736
FLAG_MOBIL                      0.000000
FLAG_EMP_PHONE                  0.000000
FLAG_WORK_PHONE                 0.000000
FLAG_CONT_MOBILE                0.000000
FLAG_PHONE                      0.000000
FLAG_EMAIL                      0.000000
OCCUPATION_TYPE                 0.313435
CNT_FAM_MEMBERS                 0.000004
REGION_RATING_CLIENT            0.000000
REGION_RATING_CLIENT_W_CITY     0.000000
WEEKDAY_APPR_PROCESS_START      0.000000
HOUR_APPR_PROCESS_START         0.000000
REG_REGION_NOT_LIVE_REGION      0.000000
REG_REGION_NOT_WORK_REGION      0.000000
LIVE_REGION_NOT_WORK_REGION     0.000000
REG_CITY_NOT_LIVE_CITY          0.000000
REG_CITY_NOT_WORK_CITY          0.000000
LIVE_CITY_NOT_WORK_CITY         0.000000
ORGANIZATION_TYPE               0.000000
EXT_SOURCE_1                    0.563281
EXT_SOURCE_2                    0.002150
EXT_SOURCE_3                    0.198212
APARTMENTS_AVG                  0.507507
BASEMENTAREA_AVG                0.585152
YEARS_BEGINEXPLUATATION_AVG     0.487681
YEARS_BUILD_AVG                 0.665402
COMMONAREA_AVG                  0.699034
ELEVATORS_AVG                   0.533027
ENTRANCES_AVG                   0.503301
FLOORSMAX_AVG                   0.497458
FLOORSMIN_AVG                   0.678746
LANDAREA_AVG                    0.593896
LIVINGAPARTMENTS_AVG            0.683866
LIVINGAREA_AVG                  0.501910
NONLIVINGAPARTMENTS_AVG         0.694673
NONLIVINGAREA_AVG               0.551982
APARTMENTS_MODE                 0.507507
BASEMENTAREA_MODE               0.585152
YEARS_BEGINEXPLUATATION_MODE    0.487681
YEARS_BUILD_MODE                0.665402
COMMONAREA_MODE                 0.699034
ELEVATORS_MODE                  0.533027
ENTRANCES_MODE                  0.503301
FLOORSMAX_MODE                  0.497458
FLOORSMIN_MODE                  0.678746
LANDAREA_MODE                   0.593896
LIVINGAPARTMENTS_MODE           0.683866
LIVINGAREA_MODE                 0.501910
NONLIVINGAPARTMENTS_MODE        0.694673
NONLIVINGAREA_MODE              0.551982
APARTMENTS_MEDI                 0.507507
BASEMENTAREA_MEDI               0.585152
YEARS_BEGINEXPLUATATION_MEDI    0.487681
YEARS_BUILD_MEDI                0.665402
COMMONAREA_MEDI                 0.699034
ELEVATORS_MEDI                  0.533027
ENTRANCES_MEDI                  0.503301
FLOORSMAX_MEDI                  0.497458
FLOORSMIN_MEDI                  0.678746
LANDAREA_MEDI                   0.593896
LIVINGAPARTMENTS_MEDI           0.683866
LIVINGAREA_MEDI                 0.501910
NONLIVINGAPARTMENTS_MEDI        0.694673
NONLIVINGAREA_MEDI              0.551982
FONDKAPREMONT_MODE              0.684202
HOUSETYPE_MODE                  0.501700
TOTALAREA_MODE                  0.482553
WALLSMATERIAL_MODE              0.508334
EMERGENCYSTATE_MODE             0.473903
OBS_30_CNT_SOCIAL_CIRCLE        0.003299
DEF_30_CNT_SOCIAL_CIRCLE        0.003299
OBS_60_CNT_SOCIAL_CIRCLE        0.003299
DEF_60_CNT_SOCIAL_CIRCLE        0.003299
DAYS_LAST_PHONE_CHANGE          0.000004
FLAG_DOCUMENT_2                 0.000000
FLAG_DOCUMENT_3                 0.000000
FLAG_DOCUMENT_4                 0.000000
FLAG_DOCUMENT_5                 0.000000
FLAG_DOCUMENT_6                 0.000000
FLAG_DOCUMENT_7                 0.000000
FLAG_DOCUMENT_8                 0.000000
FLAG_DOCUMENT_9                 0.000000
FLAG_DOCUMENT_10                0.000000
FLAG_DOCUMENT_11                0.000000
FLAG_DOCUMENT_12                0.000000
FLAG_DOCUMENT_13                0.000000
FLAG_DOCUMENT_14                0.000000
FLAG_DOCUMENT_15                0.000000
FLAG_DOCUMENT_16                0.000000
FLAG_DOCUMENT_17                0.000000
FLAG_DOCUMENT_18                0.000000
FLAG_DOCUMENT_19                0.000000
FLAG_DOCUMENT_20                0.000000
FLAG_DOCUMENT_21                0.000000
AMT_REQ_CREDIT_BUREAU_HOUR      0.135013
AMT_REQ_CREDIT_BUREAU_DAY       0.135013
AMT_REQ_CREDIT_BUREAU_WEEK      0.135013
AMT_REQ_CREDIT_BUREAU_MON       0.135013
AMT_REQ_CREDIT_BUREAU_QRT       0.135013
AMT_REQ_CREDIT_BUREAU_YEAR      0.135013
dtype: float64
0 0

In [ ]:
# may need to handle each column with different strategy, but now I just impute using most frequent one
from sklearn.preprocessing import Imputer
my_imputer = Imputer(strategy = 'most_frequent')
encoded_X_train_imputed = my_imputer.fit_transform(encoded_X_train)
encoded_X_test_imputed = my_imputer.transform(encoded_X_test)

In [ ]:
import xgboost as xgb
gbm = xgb.XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.05).fit(X_train, y_train)
predictions = gbm.predict(X_test)

# bureau_balance

In [ ]:
application_train = pd.read_csv( dataDir + 'application_train.csv' )